apiVersion: v1
kind: Secret
metadata:
  name: "artifacts-credentials"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  credentials: {{ .Values.config.objectStorage.credential | b64enc | indent 2 }}
