{{ if .Values.secrets.artifactsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.artifactsSecret.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  credentials: {{ .Values.config.objectStorage.credential | b64enc | indent 2 }}
{{ end }}
