{{ if .Values.imageRegistry.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runner.fullname" . }}-image-registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
{{- $auth := printf "%s:%s" .Values.imageRegistry.username .Values.imageRegistry.password | b64enc }}
    {
      "auths": {
        "{{ .Values.imageRegistry.registryUrl }}": {
          "username": "{{ .Values.imageRegistry.username }}",
          "password": "{{ .Values.imageRegistry.password }}",
          "auth": "{{ $auth }}"
        }
      }
    }
{{ end }}
