kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "runner-jobs"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "runner"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "runner-jobs"
  apiGroup: rbac.authorization.k8s.io
