kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "runner-jobs"
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
