{{ if .Values.secrets.runnerSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.runnerSecret.secretName }}
  namespace: {{ .Release.Namespace }}
type: Generic
data:
  config: |
{{ .Values.config | toYaml | toString | b64enc | indent 4 }}
{{ end }}
