## @section kube-scheduler configuration parameters
##

## @param config The configuration values for kube-scheduler. Ref: https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta3/
config:
  # apiVersion: kubescheduler.config.k8s.io/v1beta3
  # kind: KubeSchedulerConfiguration
  # leaderElection:
  #   leaderElect: false
  # profiles:
  #   - schedulerName: deepsource-kube-scheduler
  #     plugins:
  #       score:
  #         enabled:
  #           - name: NodeResourcesFit
  #             weight: 1
  #         disabled:
  #           - name: NodeResourcesBalancedAllocation
  #             weight: 1
  #     pluginConfig:
  #       - name: NodeResourcesFit
  #         args:
  #           scoringStrategy:
  #             type: MostAllocated
  #             resources:
  #               - name: cpu
  #                 weight: 1
  #               - name: memory
  #                 weight: 1

## @param replicaCount Number of kube-scheduler pods to run (if running in HA mode, enable `leaderElection` in config)
replicaCount: 1

## kube-scheduler image parameters
## @param image.repository The repository to use for the kube-scheduler image
## @param image.pullPolicy The pull policy for the kube-scheduler image
## @param image.tag The tag for the kube-scheduler image
image:
  repository: registry.k8s.io/kube-scheduler
  pullPolicy: IfNotPresent
  tag: v1.24.13

## @param imagePullSecrets Specify docker-registry secret names as an array
imagePullSecrets: []

## @param nameOverride String to partially override kube-scheduler.name
##
nameOverride: ""

## @param fullnameOverride String to partially override kube-scheduler.name
##
fullnameOverride: ""

## ServiceAccount configuration
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
## @param serviceAccount.create Specifies whether a ServiceAccount should be created
## @param serviceAccount.annotations Annotations for service account. Evaluated as a template. Only used if `create` is `true`.
## @param serviceAccount.name Name of the service account to use. If not set and create is true, a name is generated using the fullname template.
##
serviceAccount:
  create: true
  annotations: {}
  name: ""

## @param podAnnotations Annotations for the kube-scheduler pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## @param podSecurityContext Security context policies to add to the kube-scheduler pods
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext: {}

## @param securityContext Security context policies to add to the containers
##
securityContext: {}

## kube-scheduler resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  ## The resources limits for the kube-scheduler containers
  ##
  limits:
    ## @param resources.limits.cpu The resources limits for the kube-scheduler containers
    ##
    cpu: 100m
    ## @param resources.limits.memory The resources limits for the kube-scheduler containers
    ##
    memory: 128Mi
  ## The requested resources for the kube-scheduler containers
  ##
  requests:
    ## @param resources.requests.cpu The requested cpu for the kube-scheduler containers
    ##
    cpu: 100m
    ## @param resources.requests.memory The requested memory for the kube-scheduler containers
    ##
    memory: 128Mi

## Autoscaling parameters
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling for kube-scheduler, make sure to enable `leaderElection` in config
## @param autoscaling.minReplicas Minimum number of kube-scheduler replicas
## @param autoscaling.maxReplicas Maximum number of kube-scheduler replicas
## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
## @param autoscaling.targetMemoryUtilizationPercentage Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## @param nodeSelector Node labels for kube-scheduler pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## @param tolerations Tolerations for kube-scheduler pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## @param affinity Affinity for kube-scheduler pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
